name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - partd
  - bokeh
  - dask
  - seaborn
  - plotly_express
  - seaborn
  - scipy
  - statsmodels
  - patsy
  - jupytext
  - plotly==4.8.1
  - jupyter
  - notebook
  - pandas==1.0.3
  - statsmodels==0.11.1
  - scipy
  - patsy==0.5.1
  - requests
  - networkx
  - scikit-image
  - datashader
  - pyarrow
