name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupytext
  - jupyter
  - notebook
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - partd
  - bokeh
  - dask
  - seaborn
  - pip
  - pip:
  # works for regular pip packages
    - plotly==4.8.1
    - statsmodels==0.11.1
    - scipy
    - patsy==0.5.1
    - plotly-geo
    - requests
    - networkx
    - scikit-image
    - datashader
    - pyarrow
    - cufflinks==0.17.3
    - pdoc3>=0.5.3
    - nbconvert>=5.3.1
